### PR TITLE
either: implement Apply, Applicative, Chain, and Monad

### PR DESCRIPTION
**Pull request by davidchambers**
I *think* this is correct, but I'd greatly appreciate a review.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
LGTM. :cow2:

2 recommendations: 
1. use the `types` test file from ramda-fantasy or something like it for legal compliance; and 
2. use jsverify or something like it for property-based testing

**Comment by davidchambers** [comment]
Thank you for the recommendations, @buzzdecafe.

> use the `types` test file from ramda-fantasy or something like it for legal compliance

Good idea. This makes me wonder whether the ramda-fantasy compliance tests could live in their own package. It would be great for various libraries to share these tests.

> use jsverify or something like it for property-based testing

I watched John Hughes present the Clojure/West keynote last year: [Testing the Hard Stuff and Staying Sane][1]. I'm convinced of the value of property-based testing, but I've yet to actually use it. I should change that!


[1]: https://www.youtube.com/watch?v=zi0rHwfiX1Q

**Comment by buzzdecafe** [comment]
> the ramda-fantasy compliance tests could live in their own package. 

interesting idea. might make sense to "donate" 'em to fantasyland

**Comment by CrossEye** [comment]
LGTM

@buzzdecafe: How convinced are you by the rf test suite?  I remember a lot of doubts for a while about how much it was really telling us.

**Comment by buzzdecafe** [comment]
that's what jsverify is for

**Pull request merged**
