### PR TITLE
Add S.length function

### PR DESCRIPTION
**Pull request by svozza**
I went with the `Countable` suggestion as mentioned in #145.

### CODE REVIEW

**Comment by davidchambers** [comment]
What's the appeal of this function over `R.prop('length')`? I'm curious. :)

**Comment by svozza** [comment]
Hmmm, good question. Not a lot, aside from a more descriptive error message than:

> TypeError: Cannot read property 'length' of undefined

**Comment by svozza** [comment]
How would that work? We couldn't do something like:

```js
def('prop', {}, [$.RecordType, $.Any]...)
```

**Comment by davidchambers** [comment]
How about something like this?

```javascript
var prop =
def('prop',
    {a: [Accessible]},
    [$.String, a, b],
    function(name, obj) {
      if (name in obj) {
        return obj[name];
      } else {
        throw new TypeError('‘prop’ expected object to have a property named ' +
                            '‘' + name + '’; ' + show(obj) + ' does not');
      }
    });
```

**Comment by svozza** [comment]
Do we want to traverse the prototype chain to find properties? I know not doing so would make this an O(n) function but I think it might be less surprising to users.

**Comment by davidchambers** [comment]
How do you feel about `length` now that we have `prop`, Stefano?

**Comment by svozza** [comment]
Only seeing your comment now, David. I think we can close this one. I really don't like this `Countable` type thing.

**Comment by davidchambers** [comment]
Okay. Closing without prejudice.

**Pull request closed without merging**
