### PR TITLE
add insert delete and lookup

### PR DESCRIPTION
**Pull request by benperez**
Here's a preliminary proposal for what #24 could look like. There are definitely a lot of open questions about this but I figured it would be helpful to have something to at least look at.

I've avoided creating a new type for `S.Map` for the time being and am simply using the ES6 `Map` type.

### CODE REVIEW

**Comment by davidchambers** [comment]
`insert` and `delete` are [`R.assoc`][1] and [`R.dissoc`][2] but for Map. I suggest we first discuss in a Ramda issue the possibility of Ramda supporting Map in its "object" functions. We could think of objects as "map-like" in the same way we think of arguments objects as "array-like". I'm not sure this'll fly with @CrossEye, but it can't hurt to find out. :)


[1]: http://ramdajs.com/docs/#assoc
[2]: http://ramdajs.com/docs/#dissoc

**Comment by benperez** [comment]
Assuming something like https://github.com/ramda/ramda/pull/1056 gets merged into ramda I think that just leaves us with `S.lookup`

**Comment by buzzdecafe** [comment]
> Assuming something like ramda/ramda#1056 gets merged into ramda

I think that's a safe assumption. i'd be very surprised if we just punted on ES6 features

**Comment by davidchambers** [comment]
Rather than add `S.lookup` we could update `S.get` (and `S.gets`) to support Map objects.

**Comment by benperez** [comment]
I like the idea of paralleling the ramda API. `S.gets` feels a little weird with nested dictionaries. When I think about objects I think about collections of key value pairs where the keys are all strings and the values are of heterogeneous type. When I think about Maps I think of `Data.Map k a` where k and a are fixed types. Given that we're using JS though this is probably not a realistic use case.

**Comment by benperez** [comment]
Closing given the discussion in plaid/sanctuary/issues/24

**Pull request closed without merging**
